name: Build Apps

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Windows app
      run: npm run build
    
    - name: Upload Windows installer
      uses: actions/upload-artifact@v3
      with:
        name: windows-installer
        path: dist/*.exe

  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build macOS app
      run: npm run build-mac
    
    - name: Upload macOS installer
      uses: actions/upload-artifact@v3
      with:
        name: macos-installer
        path: dist/*.dmg